### PR TITLE
Re- implemented obj::left and obj::right functions to more closely resemble shiftit

### PR DESCRIPTION
**Pull request by saru-d2**
I implemented functionality to allow pressing mash + left or mash + right repeatedly to cycle the horizontal scale of the window to 1/2, 1/3, and 2/3 of the screen.

This is my first foray into Lua programming, so please let me know where the code could be made more efficient/ readable.

### CODE REVIEW

**Comment by saru-d2** [comment]
I have also implemented moving windows between monitors

**Review by mackinleysmith — APPROVED** [review]
I would love to see this get merged -- it would be super helpful to my workflow.

**Comment by saru-d2** [comment]
> I would love to see this get merged -- it would be super helpful to my workflow.

It doesn’t need to be merged for you to use it :)

**Comment by peterklijn** [comment]
Hi @saru-d2,

Thanks a lot for your PR, and apologies for the delay.

First of all, I really like your idea!
However, it misses a bit of flexibility, and I like to have features that deviate from ShiftIt to be opt-in. I've been playing around with the code myself, and the recent activity in this PR triggered me to finalise it.
I created a draft PR of it [here](https://github.com/peterklijn/hammerspoon-shiftit/pull/21).

It allows you to set any number of scales, in any order, for both horizontal and vertical scales.
You can configure it like this:
```lua
hs.loadSpoon("ShiftIt")
spoon.ShiftIt:bindHotkeys({})
spoon.ShiftIt:setSteps({50, 33, 67}, {50}) -- percentage values
```

I need to add some documentation, but other than that I think it's in a pretty decent shape.

Regarding the other feature you mentioned:

> I have also implemented moving windows between monitors

This is already there, you can find it in the docs as follows:

> ctrl(^) + alt(⌥) + cmd(⌘) + N Move current window to next screen
> ctrl(^) + alt(⌥) + cmd(⌘) + P Move current window to previous screen

You can override the key bindings if you prefer other ones :)

**Pull request closed without merging**
